### ISSUE TITLE
Add scripted tests

### ISSUE THREAD

**Issue by BennyHill** [typelevel/sbt-catalysts#10]
Should have done this _ages_ ago. Sorry!!

**Comment by BennyHill** [comment]
So I will finally have a bash at this one. Some thoughts before I start.

There are three (related) parts to this, as noted in the `README.md`:

1. Included plugins
2. Versions and library settings
3. Helper functions

So what should a minimal/basic scripted test do? My concern is to test enough without having to call all the plugins in (1) _and_ all the libraries from (2). (3) should really just be a case of calling all the methods in [CatalystsPlugin.scala](https://github.com/typelevel/sbt-catalysts/blob/master/src/main/scala/sbtcatalysts/CatalystsPlugin.scala) and checking correct return value or required effect.

For 1), just calling the plugin will load all the other dependent plugins, so I guess we need one test per plugin.

I guess it is (2) where I'm uncertain.  Should we have tests that:

- try and load each library,
- try and load _all_ libraries in one test project and import _all_ in one test scala file
- ???

I wonder for a first "cut", could we create a mini project with one just one Scala project with one `build.sbt` that calls each plugin, and one Scala source file that imports all the libraries. Would that be enough (to start with)?

**Comment by kailuowang** [comment]
> a mini project with one just one Scala project with one build.sbt that calls each plugin, and one Scala source file that imports all the libraries.
That sounds good to me. 👍

**Comment by BennyHill** [comment]
cool and thanks :+1:

**Comment by kailuowang** [comment]
I am working on this one as well.

**Comment by kailuowang** [comment]
done
