### ISSUE TITLE
Add 2.12 support

### ISSUE THREAD

**Issue by BennyHill** [typelevel/sbt-catalysts#11]
Basically, copy over new settings from https://github.com/typelevel/catalysts

**Comment by kailuowang** [comment]
This is done right?

**Comment by BennyHill** [comment]
Not sure, but I don't think so. I think I had in mind to add https://github.com/typelevel/catalysts/blob/master/build.sbt#L216-L273 - similar to that in cats, btw.

I can tackle this at weekend (assuming still open)

**Comment by kailuowang** [comment]
done
