### ISSUE TITLE
Preparations for sbt 1.0.0

### ISSUE THREAD

**Issue by BennyHill** [typelevel/sbt-catalysts#33]
checking against https://github.com/typelevel/cats/issues/1848, we are not far off aready

**Comment by BennyHill** [comment]
The only issue we _might_ have is tut,as 2.10.x support is dropped in for the tut sbt 1.0.0 version. 

But that might be a runtime issue only for clients to decide.

**Comment by fthomas** [comment]
Support for 2.10 was added back in tut 0.6.1.

**Comment by BennyHill** [comment]
@fthomas cool!

**Comment by kailuowang** [comment]
I am working on the migration.
